# Generated by Django 5.2.14 on 2026-07-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to='addons/')),
                ('is_available', models.BooleanField(default=True)),
                ('is_veg', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_items', models.ManyToManyField(blank=True, related_name='addons', to='menu.menuitem')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
