# Generated by Django 5.2.14 on 2026-07-09 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_addon'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, default='🍱', help_text='Emoji icon', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Daily Menus',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='DailyMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_total', models.PositiveIntegerField(default=0, help_text='Total quantity available for the day')),
                ('quantity_sold', models.PositiveIntegerField(default=0, help_text='Quantity sold so far today')),
                ('date', models.DateField(help_text='Date for which this quantity applies')),
                ('daily_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_items', to='menu.dailymenu')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_menu_entries', to='menu.menuitem')),
            ],
            options={
                'ordering': ['daily_menu', 'menu_item'],
                'unique_together': {('daily_menu', 'menu_item', 'date')},
            },
        ),
    ]
